### ISSUE TITLE
Nemesis Deck

### ISSUE THREAD

**Issue by GeneCupstid** [twistedsistem/OCTGN-Marvel-Champions#4]
Not quite sure how to deal with the nemesis deck when `Shadow of the Past` is revealed.  Should I just manually move things around?  No problem if that's the case, I want to make sure I'm not missing anything.

Sorry to hit you up again, but I'm definitely eager to get all this sorted.  I would like to do some streams of Marvel Champions, but need to figure everything out first so I don't look like an idiot more than usual.

**Comment by twistedsistem** [comment]
You are not a bother or anything!  I am excited that you are making use of it and all the work isn't just going to the side :)

I will add a nemesis function to the next update so that you can just tell it that the nemesis has been activated and it will put the scheme out and the minion in front of that player and the rest of the cards into the encounter deck.

The next update is actually going to be quite big as I am going through and reworking the flow of the game to make it more multiplayer based.  Currently if you are only playing solo all of the turn based stuff doesn't matter.  In the future it will be mainly dependent on constantly using a hotkey (currently thinking f12) for progressing the game.  So you will start your turn and then when you are done you will press f12 and it will either move to the next player or start the villain phase.  Eventually it will be press f12 and then the attack/scheme happens for the villain and then hit it again and the encounters will happen and so on and so forth.

Please let me know of any features you would like to see added to the game to make the flow of it better.

Please keep the issues coming in as you are lighting a fire under my butt to keep coding and making it better faster.

**Comment by GeneCupstid** [comment]
That sounds great.  I've been trying to do that, even on my own.  `F12` works great, 

- Once the game is fully setup, I have been hitting the play button first.
- Followed by a single `F12`.  
- After that, `F12` at the end of each turn (player, villain).  

That seems to keep everything on the right track.  @twistedsistem let me know if that isn't the proper flow.

I'm happy to help.  I've setup a whole streaming thing for this and will also record some videos to show people how doable it is to play the game.  You've done a great job!  I manage a community project as well, and it can be hard to keep it up if no one is using it or contributing.

I have a couple of keyboard shortcut ideas, from playing the game 5-6 times so far.  I'll put those in a different issue later today!
